---
- hosts: glance_all
  user: root
  tasks:
  - name: Inserted by Bhujay*******************to unmount nfs mount points
    mount:
      name: /var/lib/glance/images/
      src: /10.0.0.15:/images
      fstype: nfs
      state: unmounted
   